language: node_js

node_js:
  - "10"
  - "6"
  - "8"
  - "lts/*"
  - "node"

before_script:
  - "npm install nyc --global"

script:
  - "npm run build"
  - "nyc npm test"

after_success:
  - "npm install coveralls@~3.0.0 --global"
  - "nyc report --reporter=text-lcov | coveralls"

before_deploy:
  - "npm install"
  - "npm run clean"
  - "npm run build:prod"

deploy:
  skip_cleanup: true
  provider: releases
  file: dist/index.js
  api_key: "${GITHUB_TOKEN}"
  on:
    branch: master
    node_js: "lts/*"
